#!/bin/sh

mamba update env -n mleprae-genomics -c bioconda -c conda-forge -c defaults \
perl-bioperl >=1.7.2 \
python=3.10 \
pandas \
multiqc=1.13 \
snakemake=7.5 \
bcftools=1.15 \
trimmomatic=0.39 \
samtools=1.15 \
fastqc=0.11.9 \
freebayes=1.3.6 \
varscan=2.4.4 \
snpeff=5.1 \
bowtie2=2.4.5 \
picard=2.27.4 \
seqprep=1.3.2 \
snakemake-wrapper-utils \
qualimap=2.2.2 \
bedops=2.4.41 \
snippy=4.6.0 \
